### ISSUE TITLE
[Feature Request]: Ability to add/move/delete shared markers on map

### ISSUE THREAD

**Issue by ghostop14** [meshtastic/Meshtastic-Apple#267] opened 2022-12-14 14:34 UTC
### OS

iOS, iPadOS

### Description

It would be nice to be able to drop markers on the mobile maps.  Could be items of interest, waypoints, etc.  Would need add/update/delete capabilities on them as well.

**Comment by garthvh** [comment] 2022-12-14 14:45
Its on the list
duplicate of https://github.com/meshtastic/Meshtastic-Apple/issues/210

**Closed by garthvh** 2022-12-14 14:45 UTC
Labels: duplicate, enhancement
