### ISSUE TITLE
🚀 [Feature Request]: Sending and receiving messagese over MQTT when you are not connected to Lora device

### ISSUE THREAD

**Issue by jpbusman** [meshtastic/Meshtastic-Apple#985] opened 2024-11-05 10:42 UTC
### OS

iOS

### Description

I would like to send/receive a message over Lora and MQTT to a user without a Lora Device and receive it in the Meshtastic ios app

A kind of dummy device should be an option if no BLE device is found, device Id is generated based on the Smartphone mac

### Participation

- [ ] I am willing to sponsor this feature.
- [X] I am willing to submit a pull request for this feature.

**Comment by garthvh** [comment] 2024-11-05 15:59
Duplicate of https://github.com/meshtastic/Meshtastic-Apple/issues/412 would need to be supported in the firmware and is likely pretty problematic for the lora mesh.  Not on the roadmap anymore.

**Closed by garthvh** 2024-11-05 15:59 UTC
Labels: enhancement
